config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'
end

Spree::Core::Engine.routes.prepend do
  get '/forbidden', to: 'home#forbidden', as: :forbidden
  # those routes are needed for mailers
  root to: 'home#index'
  resources :products, only: [:index, :show]

  ##
  namespace :admin, path: Spree.admin_path do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        post :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    get '/variants/search', to: "variants#search", as: :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    get '/return_authorizations', to: "return_index#return_authorizations", as: :return_authorizations
    get '/customer_returns', to: "return_index#customer_returns", as: :customer_returns

    resource :general_settings do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :refund_reasons, except: :show
    resources :return_authorization_reasons, except: :show

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :store_credit_categories
    resources :tax_rates
    resources :trackers
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end
    resources :roles

    resources :users do
      member do
        get :addresses
        put :addresses
        put :clear_api_key
        put :generate_api_key
        get :items
        get :orders
      end
      resources :store_credits
    end
  end

  get Spree.admin_path, to: 'admin/root#index', as: :admin
  ####


  get '/locale/set', to: 'locale#set'

  # non-restful checkout stuff
  patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
  get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
  get '/checkout', to: 'checkout#edit', as: :checkout

  populate_redirect = redirect do |params, request|
    request.flash[:error] = Spree.t(:populate_get_error)
    request.referer || '/cart'
  end

  get '/orders/populate', to: populate_redirect

  resources :orders, except: [:index, :new, :create, :destroy] do
    post :populate, on: :collection
  end

  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart', to: 'orders#update', as: :update_cart
  put '/cart/empty', to: 'orders#empty', as: :empty_cart

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/content/cvv', to: 'content#cvv', as: :cvv
  get '/content/*path', to: 'content#show', as: :content
  get '/cart_link', to: 'store#cart_link', as: :cart_link

end

app/models/spree/adjustable/adjuster/promotion.rb
module Spree
  module Adjustable
    module Adjuster
      class Promotion < Spree::Adjustable::Adjuster::Base
        def update
          promo_adjustments = adjustments.competing_promos.reload.map { |a| a.update!(adjustable) }
          promos_total = promo_adjustments.compact.sum
          choose_best_promo_adjustment unless promos_total == 0
          promo_total = best_promo_adjustment.try(:amount).to_f if best_promo_adjustment.try(:promotion?)

          update_totals(promo_total)
        end

        private

        # Picks one (and only one) competing discount to be eligible for
        # this order. This adjustment provides the most discount, and if
        # two adjustments have the same amount, then it will pick the
        # latest one.
        def choose_best_promo_adjustment
          if best_promo_adjustment
            other_promotions = adjustments.competing_promos.where.not(id: best_promo_adjustment.id)
            other_promotions.update_all(eligible: false)
          end
        end

        def best_promo_adjustment
          @best_promo_adjustment ||= begin
            adjustments.competing_promos.eligible.reorder("amount ASC, created_at DESC, id DESC").first
          end
        end

        def update_totals(promo_total)
          promo_total ||= 0.0
          @totals[:promo_total] = promo_total
          @totals[:taxable_adjustment_total] += promo_total
        end
      end
    end
  end
end

app/models/spree/promotion.rb
module Spree
  class Promotion < Spree::Base
    MATCH_POLICIES = %w(all any)
    UNACTIVATABLE_ORDER_STATES = ["complete", "awaiting_return", "returned"]

    attr_reader :eligibility_errors

    belongs_to :promotion_category

    has_many :promotion_rules, autosave: true, dependent: :destroy
    alias_method :rules, :promotion_rules

    has_many :promotion_actions, autosave: true, dependent: :destroy
    alias_method :actions, :promotion_actions

    has_many :order_promotions, class_name: 'Spree::OrderPromotion'
    has_many :orders, through: :order_promotions, class_name: 'Spree::Order'

    accepts_nested_attributes_for :promotion_actions, :promotion_rules

    validates_associated :rules

    validates :name, presence: true
    validates :path, uniqueness: { allow_blank: true }
    validates :usage_limit, numericality: { greater_than: 0, allow_nil: true }
    validates :description, length: { maximum: 255 }, allow_blank: true

    before_save :normalize_blank_values

    scope :coupons, -> { where.not(code: nil) }
    scope :advertised, -> { where(advertise: true) }
    scope :applied, lambda {
      joins(<<-SQL).uniq
        INNER JOIN spree_order_promotions
        ON spree_order_promotions.promotion_id = #{table_name}.id
      SQL
    }

    self.whitelisted_ransackable_attributes = ['path', 'promotion_category_id', 'code']

    def self.with_coupon_code(coupon_code)
      where("lower(#{table_name}.code) = ?", coupon_code.strip.downcase).first
    end

    def self.active
      where('spree_promotions.starts_at IS NULL OR spree_promotions.starts_at < ?', Time.current).
        where('spree_promotions.expires_at IS NULL OR spree_promotions.expires_at > ?', Time.current)
    end

    def self.order_activatable?(order)
      order && !UNACTIVATABLE_ORDER_STATES.include?(order.state)
    end

    def expired?
      !!(starts_at && Time.current < starts_at || expires_at && Time.current > expires_at)
    end

    def activate(payload)
      order = payload[:order]
      return unless self.class.order_activatable?(order)

      payload[:promotion] = self

      # Track results from actions to see if any action has been taken.
      # Actions should return nil/false if no action has been taken.
      # If an action returns true, then an action has been taken.
      results = actions.map do |action|
        action.perform(payload)
      end
      # If an action has been taken, report back to whatever activated this promotion.
      action_taken = results.include?(true)

      if action_taken
      # connect to the order
      # create the join_table entry.
        self.orders << order
        self.save
      end

      action_taken
    end

    # called anytime order.update_with_updater! happens
    def eligible?(promotable)
      return false if expired? || usage_limit_exceeded?(promotable) || blacklisted?(promotable)
      !!eligible_rules(promotable, {})
    end

    # eligible_rules returns an array of promotion rules where eligible? is true for the promotable
    # if there are no such rules, an empty array is returned
    # if the rules make this promotable ineligible, then nil is returned (i.e. this promotable is not eligible)
    def eligible_rules(promotable, options = {})
      # Promotions without rules are eligible by default.
      return [] if rules.none?
      eligible = lambda { |r| r.eligible?(promotable, options) }
      specific_rules = rules.select { |rule| rule.applicable?(promotable) }
      return [] if specific_rules.none?

      rule_eligibility = Hash[specific_rules.map do |rule|
        [rule, rule.eligible?(promotable, options)]
      end]

      if match_all?
        # If there are rules for this promotion, but no rules for this
        # particular promotable, then the promotion is ineligible by default.
        unless rule_eligibility.values.all?
          @eligibility_errors = specific_rules.map(&:eligibility_errors).detect(&:present?)
          return nil
        end
        specific_rules
      else
        unless rule_eligibility.values.any?
          @eligibility_errors = specific_rules.map(&:eligibility_errors).detect(&:present?)
          return nil
        end

        [rule_eligibility.detect { |_, eligibility| eligibility }.first]
      end
    end

    def products
      rules.where(type: "Spree::Promotion::Rules::Product").map(&:products).flatten.uniq
    end

    def usage_limit_exceeded?(promotable)
      usage_limit.present? && usage_limit > 0 && adjusted_credits_count(promotable) >= usage_limit
    end

    def adjusted_credits_count(promotable)
      adjustments = promotable.is_a?(Order) ? promotable.all_adjustments : promotable.adjustments
      credits_count - adjustments.promotion.where(source_id: actions.pluck(:id)).size
    end

    def credits
      Adjustment.eligible.promotion.where(source_id: actions.map(&:id))
    end

    def credits_count
      credits.count
    end

    def line_item_actionable?(order, line_item)
      if eligible? order
        rules = eligible_rules(order)
        if rules.blank?
          true
        else
          rules.send(match_all? ? :all? : :any?) do |rule|
            rule.actionable? line_item
          end
        end
      else
        false
      end
    end

    def used_by?(user, excluded_orders = [])
      [
        :adjustments,
        :line_item_adjustments,
        :shipment_adjustments
      ].any? do |adjustment_type|
        user.orders.complete.joins(adjustment_type).where(
          spree_adjustments: {
            source_type: 'Spree::PromotionAction',
            source_id: actions.map(&:id),
            eligible: true
          }
        ).where.not(
          id: excluded_orders.map(&:id)
        ).any?
      end
    end

    private
    def blacklisted?(promotable)
      case promotable
      when Spree::LineItem
        !promotable.product.promotionable?
      when Spree::Order
        promotable.line_items.any? &&
          !promotable.line_items.joins(:product).where(spree_products: {promotionable: true}).any?
      end
    end

    def normalize_blank_values
      [:code, :path].each do |column|
        self[column] = nil if self[column].blank?
      end
    end

    def match_all?
      match_policy == 'all'
    end
  end
end

app/models/spree/promotion/actions/create_adjustment.rb
module Spree
  class Promotion
    module Actions
      class CreateAdjustment < PromotionAction
        include Spree::CalculatedAdjustments
        include Spree::AdjustmentSource

        before_validation -> { self.calculator ||= Calculator::FlatPercentItemTotal.new }

        def perform(options = {})
          order = options[:order]
          create_unique_adjustment(order, order)
        end

        def compute_amount(order)
          [(order.item_total + order.ship_total), compute(order)].min * -1
        end
      end
    end
  end
end

app/models/spree/promotion/actions/create_item_adjustments.rb
module Spree
  class Promotion
    module Actions
      class CreateItemAdjustments < PromotionAction
        include Spree::CalculatedAdjustments
        include Spree::AdjustmentSource

        before_validation -> { self.calculator ||= Calculator::PercentOnLineItem.new }

        def perform(options = {})
          order, promotion = options[:order], options[:promotion]
          create_unique_adjustments(order, order.line_items) do |line_item|
            promotion.line_item_actionable?(order, line_item)
          end
        end

        def compute_amount(line_item)
          return 0 unless promotion.line_item_actionable?(line_item.order, line_item)
          [line_item.amount, compute(line_item)].min * -1
        end
      end
    end
  end
end

app/models/spree/promotion/actions/free_shipping.rb
module Spree
  class Promotion
    module Actions
      class FreeShipping < Spree::PromotionAction
        include Spree::AdjustmentSource

        def perform(payload={})
          order = payload[:order]
          create_unique_adjustments(order, order.shipments)
        end

        def compute_amount(shipment)
          shipment.cost * -1
        end
      end
    end
  end
end

app/models/spree/promotion/rules/first_order.rb
module Spree
  class Promotion
    module Rules
      class FirstOrder < PromotionRule
        attr_reader :user, :email

        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def eligible?(order, options = {})
          @user = order.try(:user) || options[:user]
          @email = order.email

          if user || email
            if !completed_orders.blank? && completed_orders.first != order
              eligibility_errors.add(:base, eligibility_error_message(:not_first_order))
            end
          else
            eligibility_errors.add(:base, eligibility_error_message(:no_user_or_email_specified))
          end

          eligibility_errors.empty?
        end

        private
          def completed_orders
            user ? user.orders.complete : orders_by_email
          end

          def orders_by_email
            Spree::Order.where(email: email).complete
          end
      end
    end
  end
end

app/models/spree/promotion/rules/user_logged_in.rb
module Spree
  class Promotion
    module Rules
      class UserLoggedIn < PromotionRule
        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def eligible?(order, options = {})
          unless order.user.present?
            eligibility_errors.add(:base, eligibility_error_message(:no_user_specified))
          end
          eligibility_errors.empty?
        end
      end
    end
  end
end

app/controllers/spree/admin/promotions_controller.rb
module Spree
  module Admin
    class PromotionsController < ResourceController
      before_action :load_data

      helper 'spree/promotion_rules'

      protected
        def location_after_save
          spree.edit_admin_promotion_url(@promotion)
        end

        def load_data
          @calculators = Rails.application.config.spree.calculators.promotion_actions_create_adjustments
          @promotion_categories = Spree::PromotionCategory.order(:name)
        end

        def collection
          return @collection if defined?(@collection)
          params[:q] ||= HashWithIndifferentAccess.new
          params[:q][:s] ||= 'id desc'

          @collection = super
          @search = @collection.ransack(params[:q])
          @collection = @search.result(distinct: true).
            includes(promotion_includes).
            page(params[:page]).
            per(params[:per_page] || Spree::Config[:promotions_per_page])
        end

        def promotion_includes
          [:promotion_actions]
        end
    end
  end
end

app/views/spree/admin/promotions/_actions.html.erb
<div class="panel-heading">
  <h1 class="panel-title">
    <%= Spree.t(:promotion_actions) %>
  </h1>
</div>
<div id="action_fields" class="panel-body">
  <%= form_tag spree.admin_promotion_promotion_actions_path(@promotion), :remote => true, :id => 'new_promotion_action_form' do %>
    <% options = options_for_select(  Rails.application.config.spree.promotions.actions.map(&:name).map {|name| [ Spree.t("promotion_action_types.#{name.demodulize.underscore}.name"), name] } ) %>

    <div class="form-group">
      <%= label_tag :action_type, Spree.t(:add_action_of_type)%>
      <%= select_tag 'action_type', options, :class => 'select2' %>
    </div>
    <div class="form-actions">
      <%= button Spree.t(:add), 'plus', 'submit', class: "btn-success" %>
    </div>

  <% end %>

  <%= form_for @promotion, :url => spree.admin_promotion_path(@promotion), :method => :put do |f| %>
    <div id="actions" class="filter_list margint">
      <% if @promotion.actions.any? %>
        <%= render :partial => 'promotion_action',  :collection => @promotion.actions %>
      <% else %>
        <div class="alert alert-warning">
          <%= Spree.t(:no_actions_added) %>
        </div>
      <% end %>
    </div>
    <div class="actions promotion-update">
      <%= button Spree.t('actions.update'), 'save' %>
    </div>
  <% end %>

</div>

app/views/spree/admin/promotions/_form.html.erb
<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @promotion } %>

<div class="row" id="general_fields" >
  <div class="col-md-3">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :code, class: ['form-group'] do %>
      <%= f.label :code %>
      <%= f.text_field :code, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :path, class: ['form-group'] do %>
      <%= f.label :path %>
      <%= f.text_field :path, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :advertise, class: ['checkbox'] do %>
      <%= f.label :advertise do %>
        <%= f.check_box :advertise %>
        <%= Spree.t(:advertise) %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :description, class: ['form-group'] do %>
      <%= f.label :description %>
      <%= f.text_area :description, :rows => 7, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :category, class: ['form-group'] do %>
      <%= f.label :promotion_category %>
      <%= f.collection_select(:promotion_category_id, @promotion_categories, :id, :name, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2' }) %>
    <% end %>
  </div>

  <div id="expiry_fields" class="col-md-3">
    <%= f.field_container :usage_limit do %>
      <%= f.label :usage_limit %>
      <%= f.number_field :usage_limit, :min => 0, :class => 'form-control' %>
      <p class="help-block">
        <%= Spree.t(:current_promotion_usage, :count => @promotion.credits_count) %>
      </p>
    <% end %>

    <div id="starts_at_field" class="form-group">
      <%= f.label :starts_at %>
      <%= f.text_field :starts_at, :value => datepicker_field_value(@promotion.starts_at), :class => 'datepicker datepicker-from form-control' %>
    </div>

    <div id="expires_at_field" class="form-group">
      <%= f.label :expires_at %>
      <%= f.text_field :expires_at, :value => datepicker_field_value(@promotion.expires_at), :class => 'datepicker datepicker-to form-control' %>
    </div>
  </div>
</div>

app/views/spree/admin/promotions/_promotion_action.html.erb
<div class="promotion_action promotion-block <%= promotion_action.type.to_s.demodulize.underscore %> panel panel-default" id="<%= dom_id promotion_action %>">
  <% type_name = promotion_action.class.name.demodulize.underscore %>
  <div class="panel-heading">
    <%= link_to_with_icon 'delete', '', spree.admin_promotion_promotion_action_path(@promotion, promotion_action), remote: true, method: :delete, class: 'delete pull-right' %>
    <h3 class="panel-title promotion-title"><%= Spree.t("promotion_action_types.#{type_name}.description") %></h3>
  </div>
  <% param_prefix = "promotion[promotion_actions_attributes][#{promotion_action.id}]" %>
  <%= hidden_field_tag "#{param_prefix}[id]", promotion_action.id %>

  <%= render partial: "spree/admin/promotions/actions/#{type_name}",
             locals: { promotion_action: promotion_action, param_prefix: param_prefix } rescue nil %>
</div>

app/views/spree/admin/promotions/_promotion_rule.html.erb
<div class="promotion_rule promotion-block panel panel-default" id="<%= dom_id promotion_rule %>">
  <% type_name = promotion_rule.class.name.demodulize.underscore %>
  <div class="panel-heading">
    <%= link_to_with_icon 'delete', '', spree.admin_promotion_promotion_rule_path(@promotion, promotion_rule), remote: true, method: :delete, class: 'delete pull-right' %>
    <h3 class='panel-title promotion-title <%= 'no-text' if type_name == 'user_logged_in' || type_name == 'first_order'%>'><%= Spree.t("promotion_rule_types.#{type_name}.description") %></h3>
  </div>
  <% param_prefix = "promotion[promotion_rules_attributes][#{promotion_rule.id}]" %>
  <%= hidden_field_tag "#{param_prefix}[id]", promotion_rule.id %>

  <%= render partial: "spree/admin/promotions/rules/#{type_name}", locals: { promotion_rule: promotion_rule, param_prefix: param_prefix } rescue nil %>
</div>

app/views/spree/admin/promotions/_rules.html.erb
<div class="panel-heading">
  <h1 class="panel-title">
    <%= Spree.t(:rules) %>
  </h1>
</div>
<div id="rule_fields" class="panel-body">

  <%= form_tag spree.admin_promotion_promotion_rules_path(@promotion), :remote => true, :id => 'new_product_rule_form' do %>
    
    <div class="form-group">
      <%= label_tag :promotion_rule_type, Spree.t(:add_rule_of_type) %>
      <%= select_tag('promotion_rule[type]', options_for_promotion_rule_types(@promotion), :class => 'select2') %>
    </div>
    <div class="form-actions">
      <%= button Spree.t(:add), 'plus', 'submit', class: "btn-success" %>
    </div>

  <% end %>

  <%= form_for @promotion, :url => object_url, :method => :put do |f| %>
    <div id="promotion-policy-select">
      <% Spree::Promotion::MATCH_POLICIES.each do |policy| %>
        <div class="radio">
          <%= f.label "match_policy_#{policy}" do %>
            <%= f.radio_button :match_policy, policy %>
            <%= Spree.t "promotion_form.match_policies.#{policy}" %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div id="rules" class="filter_list margint">
      <% if @promotion.rules.any? %>
        <%= render :partial => 'promotion_rule', :collection => @promotion.rules, :locals => {} %>
      <% else %>
        <div class="alert alert-warning">
          <%= Spree.t(:no_rules_added) %>
        </div>
      <% end %>
    </div>

    <div class="promotion-update actions">
      <%= button Spree.t('actions.update'), 'ok' %>
    </div>    
  <% end %>
</div>

app/views/spree/admin/promotions/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:promotions), admin_promotions_url %> /
  <%= @promotion.name %>
<% end %>

<%= form_for @promotion, :url => object_url, :method => :put do |f| %>
  <div class="row">
    <div class="col-md-12">
      <%= render :partial => 'form', :locals => { :f => f } %>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </div>
  </div>

<% end %>

<div id="promotion-filters" class="row">
  <div id="rules_container" class="col-md-6">
    <div class="panel panel-default">
      <%= render :partial => 'rules' %>
    </div>
  </div>

  <div id="actions_container" class="col-md-6">
    <div class="panel panel-default">
      <%= render :partial => 'actions' %>
    </div>
  </div>
</div>

<%= render :partial => "spree/admin/variants/autocomplete", :formats => [:js] %>

app/views/spree/admin/promotions/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Promotion) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_promotion), new_object_url, :class => "btn-success", :icon => 'add' %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_promotions_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, tabindex: 1, class: "form-control js-quick-search-target" %>
          </div>

          <div class="form-group">
            <%= label_tag :q_code_cont, Spree.t(:code) %>
            <%= f.text_field :code_cont, tabindex: 1, class: "form-control" %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_path_cont, Spree.t(:path) %>
            <%= f.text_field :path_cont, tabindex: 1, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= label_tag :q_promotion_category_id_eq, Spree.t(:promotion_category) %>
            <%= f.collection_select(:promotion_category_id_eq, @promotion_categories, :id, :name, { :include_blank => Spree.t('match_choices.all') }, { :class => 'select2' }) %>
          </div>
        </div>
      </div>

      <div data-hook="admin_promotions_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @promotions %>

<% if @promotions.any? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:code) %></th>
        <th><%= Spree.t(:description) %></th>
        <th><%= Spree.t(:usage_limit) %></th>
        <th><%= Spree.t(:promotion_uses) %></th>
        <th><%= Spree.t(:expiration) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @promotions.each do |promotion| %>
        <tr id="<%= spree_dom_id promotion %>">
          <td><%= link_to promotion.name, edit_admin_promotion_path(promotion) %></td>
          <td><%= promotion.code %></td>
          <td><%= promotion.description %></td>
          <td><%= promotion.usage_limit.nil? ? "∞" : promotion.usage_limit  %></td>
          <td><%= Spree.t(:current_promotion_usage, :count => promotion.credits_count) %></td>
          <td><%= promotion.expires_at.to_date.to_s(:short_date) if promotion.expires_at %></td>
          <td class="actions actions-2">
            <%= link_to_edit promotion, :no_text => true %>
            <%= link_to_delete promotion, :no_text => true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Promotion)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

app/views/spree/admin/promotions/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:promotions), admin_promotions_url %> /
  <%= Spree.t(:new_promotion) %>
<% end %>

<%= form_for :promotion, :url => collection_url do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <div class="text-center">
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </div>
<% end %>